const url = {
    new_releases: "/api/new-releases",
    album_search: "/api/search/albums/",
    playlist_search: "/api/search/playlists/",
    artist_search: "/api/search/artists/",
    track_search: "/api/search/tracks/",
    favorite_track: "/favorite/track",
    favorite_album: "/favorite/album",
    favorite_artist: "/favorite/artist",
    favorite_playlist: "/favorite/playlist",
    favorite_delete_track: "/favorite/delete/track/",
    favorite_delete_album: "favorite/delete/album/",
    favorite_delete_artist: "/favorite/delete/artist/",
    favorite_delete_playlist: "/favorite/delete/playlist/",
    favorite_all: "/favorite/get-all",
    playlist: "/playlist/",
    playlist_new: "/playlist/new/",
    playlist_get_all: "/playlist/get-all",
    playlist_add_track: "/playlist/track/",
    playlist_delete_track: "/playlist/delete/track/",
    signup: "/user/signup",
    login: "/auth/login",
};

export default url;
